# Generated by Django 5.0.4 on 2024-07-31 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_imagen_servicio_imagen_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen_principal',
        ),
        migrations.AlterField(
            model_name='imagenservicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios_imagen/'),
        ),
        migrations.AlterField(
            model_name='imagenservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
