# Generated by Django 5.0.4 on 2024-07-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_servicio_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='servicios_imagen/'),
        ),
        migrations.AlterField(
            model_name='imagenservicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios_imagen_adicionales/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
